python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower8 --prompt an tropical island of radiant flowers and a mountain waterfall rendered in unreal engine --sigma 5.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 0.8 --normmaxcrop 0.8 --geoloss --colordepth 2 --normdepth 10 --frontview --frontview_std 4 --clipavg view --lr_decay 0.9 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 1500 --learning_rate 0.0005 --normal_learning_rate 0.0005 --background 1 1 1 --frontview_center 1.96349 0.628 --width 512
python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower8 --prompt an tropical island of radiant flowers and a mountain waterfall rendered in unreal engine --sigma 5.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 0.6 --normmaxcrop 0.6 --geoloss --colordepth 2 --normdepth 10 --frontview --frontview_std 4 --clipavg view --lr_decay 0.09 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 3000 --learning_rate 0.005 --normal_learning_rate 0.005 --background 1 1 1 --frontview_center 1.96349 0.628 --width 1024
python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower8 --prompt an tropical island of radiant flowers and a mountain waterfall rendered in unreal engine --sigma 5.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 0.4 --normmaxcrop 0.4 --geoloss --colordepth 2 --normdepth 10 --frontview --frontview_std 2 --clipavg view --lr_decay 0.009 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 6000 --learning_rate 0.05 --normal_learning_rate 0.05 --background 1 1 1 --frontview_center 1.96349 0.628 --width 2048

python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower9 --prompt an island beach full of pretty flowers and a niagra waterfall rendered in unreal engine artstation --sigma 5.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 0.9 --normmaxcrop 0.9 --geoloss --colordepth 2 --normdepth 10 --frontview --frontview_std 4 --clipavg view --lr_decay 0.9 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 1500 --learning_rate 0.0005 --normal_learning_rate 0.0005 --background 1 1 1 --frontview_center 1.96349 0.628 --width 512
python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower9 --prompt an island beach full of pretty flowers and a niagra waterfall rendered in unreal engine artstation --sigma 8.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 0.9 --normmaxcrop 0.9 --geoloss --colordepth 2 --normdepth 10 --frontview --frontview_std 4 --clipavg view --lr_decay 0.9 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 1500 --learning_rate 0.0005 --normal_learning_rate 0.0005 --background 1 1 1 --frontview_center 1.96349 0.628 --width 1024
python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower9 --prompt an island beach full of pretty flowers and a niagra waterfall rendered in unreal engine artstation --sigma 12.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 0.9 --normmaxcrop 0.9 --geoloss --colordepth 2 --normdepth 10 --frontview --frontview_std 4 --clipavg view --lr_decay 0.9 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 1500 --learning_rate 0.0005 --normal_learning_rate 0.0005 --background 1 1 1 --frontview_center 1.96349 0.628 --width 2048

python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower10 --prompt a tiny planet island tropical paradise with palm trees and a waterfall rendered in unreal engine blender cycles --sigma 5.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 0.4 --normmaxcrop 0.4 --geoloss --colordepth 2 --normdepth 10 --frontview --frontview_std 4 --clipavg view --lr_decay 0.9 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 500 --learning_rate 0.05 --normal_learning_rate 0.0005 --background 1 1 1 --frontview_center 1.96349 0.628 --width 512
python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower10 --prompt a tiny planet island tropical paradise with palm trees and a waterfall rendered in unreal engine blender cycles --sigma 5.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 0.4 --normmaxcrop 0.4 --geoloss --colordepth 4 --normdepth 10 --frontview --frontview_std 2 --clipavg view --lr_decay 0.9 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 1500 --learning_rate 0.005 --normal_learning_rate 0.0005 --background 1 1 1 --frontview_center 1.96349 0.628 --width 1024
python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower10 --prompt a tiny planet island tropical paradise with palm trees and a waterfall rendered in unreal engine blender cycles --sigma 5.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 0.4 --normmaxcrop 0.4 --geoloss --colordepth 8 --normdepth 10 --frontview --frontview_std 1 --clipavg view --lr_decay 0.9 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 9000 --learning_rate 0.005 --normal_learning_rate 0.0005 --background 1 1 1 --frontview_center 1.96349 0.628 --width 2048

python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower11 --prompt a 360 image of a island full of colorful glowing flowers and a beautiful waterfall rendered in unreal engine --sigma 5.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 0.1 --normmaxcrop 0.2 --geoloss --colordepth 2 --normdepth 10 --frontview --frontview_std 4 --clipavg view --lr_decay 0.9 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 500 --learning_rate 0.0005 --normal_learning_rate 0.0005 --background 1 1 1 --frontview_center 1.96349 0.628 --width 512
python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower11 --prompt a 360 image of a island full of colorful glowing flowers and a beautiful waterfall rendered in unreal engine --sigma 5.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 0.1 --normmaxcrop 0.2 --geoloss --colordepth 2 --normdepth 10 --frontview --frontview_std 4 --clipavg view --lr_decay 0.9 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 1500 --learning_rate 0.0005 --normal_learning_rate 0.0005 --background 1 1 1 --frontview_center 1.96349 0.628 --width 1024
python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower11 --prompt a 360 image of a island full of colorful glowing flowers and a beautiful waterfall rendered in unreal engine --sigma 5.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 0.1 --normmaxcrop 0.2 --geoloss --colordepth 2 --normdepth 10 --frontview --frontview_std 4 --clipavg view --lr_decay 0.9 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 3000 --learning_rate 0.0005 --normal_learning_rate 0.0005 --background 1 1 1 --frontview_center 1.96349 0.628 --width 2048

python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower12 --prompt a 3D rendering of uncharted island full of colorful glowing flowers and a beach and a beautiful waterfall rendered in unreal engine crysis --sigma 5.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 0.1 --normmaxcrop 0.2 --geoloss --colordepth 2 --normdepth 10 --frontview --frontview_std 4 --clipavg view --lr_decay 0.9 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 500 --learning_rate 0.0005 --normal_learning_rate 0.0005 --background 1 1 1 --frontview_center 1.96349 0.628 --width 512
python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower12 --prompt a 3D rendering of uncharted island full of colorful glowing flowers and a beach and a beautiful waterfall rendered in unreal engine crysis --sigma 3.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 0.1 --normmaxcrop 0.2 --geoloss --colordepth 2 --normdepth 10 --frontview --frontview_std 4 --clipavg view --lr_decay 0.9 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 1500 --learning_rate 0.0005 --normal_learning_rate 0.0005 --background 1 1 1 --frontview_center 1.96349 0.628 --width 1024
python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower12 --prompt a 3D rendering of uncharted island full of colorful glowing flowers and a beach and a beautiful waterfall rendered in unreal engine crysis --sigma 1.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 0.1 --normmaxcrop 0.2 --geoloss --colordepth 2 --normdepth 10 --frontview --frontview_std 4 --clipavg view --lr_decay 0.9 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 3000 --learning_rate 0.0005 --normal_learning_rate 0.0005 --background 1 1 1 --frontview_center 1.96349 0.628 --width 2048


python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower13 --prompt a planet of tropical paradise full of colorful palm trees and beach and a beautiful waterfall rendered in unreal engine 5 --sigma 2.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 1.0 --normmaxcrop 1.0 --geoloss --colordepth 2 --normdepth 10 --frontview --frontview_std 4 --clipavg view --lr_decay 0.9 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 1500 --learning_rate 0.0005 --normal_learning_rate 0.0005 --background 1 1 1 --frontview_center 1.96349 0.628 --width 512
python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower13 --prompt a planet of tropical paradise full of colorful palm trees and beach and a beautiful waterfall rendered in unreal engine 5 --sigma 7.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 1.0 --normmaxcrop 1.0 --geoloss --colordepth 2 --normdepth 10 --frontview --frontview_std 4 --clipavg view --lr_decay 0.09 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 2000 --learning_rate 0.005 --normal_learning_rate 0.005 --background 1 1 1 --frontview_center 1.96349 0.628 --width 1024
python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower13 --prompt a planet of tropical paradise full of colorful palm trees and beach and a beautiful waterfall rendered in unreal engine 5 --sigma 25.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 1.0 --normmaxcrop 1.0 --geoloss --colordepth 2 --normdepth 10 --frontview --frontview_std 4 --clipavg view --lr_decay 0.009 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 5000 --learning_rate 0.05 --normal_learning_rate 0.05 --background 1 1 1 --frontview_center 1.96349 0.628 --width 2048

python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower14 --prompt a hidden cove tiny planet full of colorful glowing fish and a coconut trees with a waterfall rendered in unreal engine artstation --sigma 3.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 0.9 --normmaxcrop 0.9 --geoloss --colordepth 2 --normdepth 10 --frontview --frontview_std 4 --clipavg view --lr_decay 0.9 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 1500 --learning_rate 0.0005 --normal_learning_rate 0.0005 --background 1 1 1 --frontview_center 1.96349 0.628 --width 512
python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower14 --prompt a hidden cove tiny planet full of colorful glowing fish and a coconut trees with a waterfall rendered in unreal engine artstation --sigma 15.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 0.7 --normmaxcrop 0.7 --geoloss --colordepth 2 --normdepth 10 --frontview --frontview_std 4 --clipavg view --lr_decay 0.09 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 3000 --learning_rate 0.005 --normal_learning_rate 0.005 --background 1 1 1 --frontview_center 1.96349 0.628 --width 1024
python main.py --run branch --obj_path data/source_meshes/vase.obj --output_dir results/demo/vase/flower14 --prompt a hidden cove tiny planet full of colorful glowing fish and a coconut trees with a waterfall rendered in unreal engine artstation --sigma 30.0 --clamp tanh --n_normaugs 4 --n_augs 1 --normmincrop 0.5 --normmaxcrop 0.5 --geoloss --colordepth 2 --normdepth 10 --frontview --frontview_std 4 --clipavg view --lr_decay 0.09 --clamp tanh --normclamp tanh --maxcrop 1.0 --save_render --seed 1 --n_iter 6000 --learning_rate 0.05 --normal_learning_rate 0.005 --background 1 1 1 --frontview_center 1.96349 0.628 --width 2048